### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/guidance-for-geospatial-insights-for-sustainability-on-aws#8]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by tamara-h** [comment]
PR merged

**Comment by vprince1** [comment]
I still see some old versions of the package. Can these be updated too? Thanks
![image](https://github.com/aws-solutions-library-samples/guidance-for-geospatial-insights-for-sustainability-on-aws/assets/11996632/49a7eb2b-4618-4d12-aea6-4960d9e98fb9)
